version: '3'
services:
  db:
    image: 'mysql:5.7'
    volumes:
      - 'db_data:/var/lib/mysql'
      - './db:/docker-entrypoint-initdb.d'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=changeit
      - MYSQL_ROOT_HOST=%
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_USER=tractteam
      - MYSQL_PASSWORD=changeit
      - MYSQL_DATABASE=tract
    ports:
      - '3306:3306'
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - '-u'
        - $MYSQL_USER
        - '--password=$MYSQL_PASSWORD'
        - ping
      interval: 10s
      timeout: 5s
      retries: 3
    command: '--default-authentication-plugin=mysql_native_password'
  phpmyadmin:
    depends_on:
      - db
    image: 'phpmyadmin/phpmyadmin:latest'
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: changeit
  frontend:
    image: node
    container_name: nodejs
    volumes:
      - '.:/home/node/app'
      - 'node_modules:/home/node/app/node_modules'
    ports:
      - '4500:3000'
      - '9000:9000'
    command: bash -c "cd home/node/app && yarn && yarn global add serve && yarn run start-serve"
  eclipse-mosquitto:
    image: eclipse-mosquitto
    ports:
      - '8883:8883'
    volumes:
      - './Docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf'
      - './Docker/mosquitto/passwordFile/passwd:/etc/mosquitto/passwd'
volumes:
  db_data: null
  node_modules: null
  db: null
