version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    networks:
      - website
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 12345678 
    networks:
      - website

  # node
  node:
    image: node
    container_name: nodejs
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - '2000:3000'
    networks:
      - website
    command: bash -c "cd home/node/app && yarn && yarn start"

networks:
  website:
volumes:
  db_data:
  node_modules: