version: '3'
services:
  eclipse-mosquitto:
    image: eclipse-mosquitto
    ports:
      - '1883:1883'
      - '9001:9001'
      - 8083:8083
      - 8883:8883
    volumes:
      - './Docker/mosquitto/:/mosquitto/config/'
      - './Docker/mosquitto/passwordFile/:/etc/mosquitto/'
    # command: mosquitto_passwd -c /etc/mosquitto/passwd tractteam
volumes:
  db_data: null
  node_modules: null
  db: null
