apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: eclipse-mosquitto
  name: eclipse-mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eclipse-mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: eclipse-mosquitto
    spec:
      containers:
        - image: eclipse-mosquitto
          name: eclipse-mosquitto
          ports:
            - containerPort: 1883
            - containerPort: 9001
            - containerPort: 8083
            - containerPort: 8883
          resources: {}
          volumeMounts:
            - mountPath: /mosquitto/config/mosquitto.conf
              name: eclipse-mosquitto-claim0
            - mountPath: /etc/mosquitto/passwd
              name: eclipse-mosquitto-claim1
      restartPolicy: Always
      volumes:
        - name: eclipse-mosquitto-claim0
          persistentVolumeClaim:
            claimName: eclipse-mosquitto-claim0
        - name: eclipse-mosquitto-claim1
          persistentVolumeClaim:
            claimName: eclipse-mosquitto-claim1
status: {}
