apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: eclipse-mosquitto
  name: eclipse-mosquitto
spec:
  ports:
    - name: "1883"
      port: 1883
      targetPort: 1883
    - name: "9001"
      port: 9001
      targetPort: 9001
    - name: "8083"
      port: 8083
      targetPort: 8083
    - name: "8883"
      port: 8883
      targetPort: 8883
  selector:
    io.kompose.service: eclipse-mosquitto
status:
  loadBalancer: {}
