apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
    - name: "4500"
      port: 4500
      targetPort: 3000
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
